### ISSUE TITLE
Allow a quiet mode

### ISSUE THREAD

**Issue by GaryJones** [felixzapata/gulp-potomo#3]
Right now, there are a couple of `console.log()` messages from this plugin, that I'd like to be able to disable. See:

![screenshot showing gulp build process](https://user-images.githubusercontent.com/88371/29239939-180401a0-7f52-11e7-9f9a-587dbe049c4d.png)

Would it be possible to support an argument to `potomo()` (how we're using it [here](https://github.com/craigsimps/gulp-wp-toolkit/blob/master/tasks/build/potomo.js)) to allow the console messages to be disabled i.e. `quiet`?

**Comment by felixzapata** [comment]
hi @GaryJones, I can add a verbosity option with a default value set to `false`.

**Comment by GaryJones** [comment]
Sounds good to me. I'm ambivalent as to whether a verbosity option should be true or false by default - I'll be running it as `false` (quiet), but it would seem the backwards-compatible default would be `true`.
